export const CHECK_BOOKING_REQUEST = "CHECK_BOOKING_REQUEST"
export const CHECK_BOOKING_SUCCESSFULL = "CHECK_BOOKING_SUCCESSFULL"
export const CHECK_BOOKING_RESET = "CHECK_BOOKING_RESET"
export const CHECK_BOOKING_FAILURE = "CHECK_BOOKING_FAILURE"

export const BOOKED_DATES_SUCCESSFULL = "BOOKED_DATES_SUCCESSFULL"
export const BOOKED_DATES_FAILURE = "BOOKED_DATES_FAILURE"

export const MY_BOOKINGS_SUCCESSFULL = "MY_BOOKINGS_SUCCESSFULL"
export const MY_BOOKINGS_FAILURE = "MY_BOOKINGS_FAILURE"

export const BOOKING_DETAILS_SUCCESSFULL = "BOOKING_DETAILS_SUCCESSFULL"
export const BOOKING_DETAILS_FAILURE = "BOOKING_DETAILS_FAILURE"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
