export const CHECK_BOOKING_REQUEST = "CHECK_BOOKING_REQUEST"
export const CHECK_BOOKING_SUCCESSFULL = "CHECK_BOOKING_SUCCESSFULL"
export const CHECK_BOOKING_RESET = "CHECK_BOOKING_RESET"
export const CHECK_BOOKING_FAILURE = "CHECK_BOOKING_FAILURE"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
