export const ALL_ROOMS_SUCCESSFULL = "ALL_ROOMS_SUCCESSFULL"
export const ALL_ROOMS_FAILURE = "ALL_ROOMS_FAILURE"

export const ROOM_DETAILS_SUCCESSFULL = "ROOMS_DETAILS_SUCCESSFULL"
export const ROOM_DETAILS_FAILURE = "ROOMS_DETAILS_FAILURE"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
