export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESSFULL = "REGISTER_USER_SUCCESSFULL"
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
