export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESSFULL = "REGISTER_USER_SUCCESSFULL"
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE"

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESSFULL = "LOAD_USER_SUCCESSFULL"
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESSFULL = "UPDATE_USER_SUCCESSFULL"
export const UPDATE_USER_RESET = "UPDATE_USER_RESET"
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE"

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESSFULL = "FORGOT_PASSWORD_SUCCESSFULL"
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE"

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESSFULL = "RESET_PASSWORD_SUCCESSFULL"
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
